services:
  node:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - NEO4J_URL=${NEO4J_URL}
    volumes:
      - ./:/home/node/app
    expose:
      - "${NODE_PORT}"
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    command: "npm run dev"
    depends_on:
      - neo4j
    restart: always

  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_config:/config
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWRD}
    ports:
      - "${NEO4J_PORT}:${NEO4J_PORT}"
      - "7474:7474"
    restart: always

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_config:
  neo4j_plugins: